### ISSUE TITLE
How can i get the report result of 0.40+ in BlogCatalog dataset (Node Classfication)?

### ISSUE THREAD

**Issue by HaoranDeng** [AnryYang/NRP-code#1]
I run the BlogCatalog dataset in the default configuration, but what I only get the best result is less than 0.36, how can I get the paper result which is 0.40+.

**Comment by AnryYang** [comment]
Did you normalize the two embedding vectors respectively, before concatenating them as final embedding vectors and inputting them to the classifier?
Please try the classifier provided at https://github.com/Josiah96Zhang/Lemane. They did normalization and got the desired result in their paper.

**Comment by HaoranDeng** [comment]
I think you may have uploaded the wrong adjacency matrix of the blogcatalog3 dataset. I downloaded the dataset from the link given in README, and found that the non-zero elements in the matrix are about 10 times the number of edges as the report. Thank you for your reply:)
